apiVersion: v1
kind: Pod
metadata:
  name: label-example
  labels:
    env: development
spec:
  containers:
  - name: label-ex
    image: quay.io/openshiftlabs/simpleservice:0.5.0
    ports:
    - containerPort: 9876